In [1]:
import numpy as np

# 1D Array

In [2]:
my_array = np.array([3,9,4,2,8,6,1,0,7,3,9])

In [3]:
my_array

array([3, 9, 4, 2, 8, 6, 1, 0, 7, 3, 9])

In [4]:
print(type(my_array))

<class 'numpy.ndarray'>


In [6]:
np.size(my_array)

11

In [7]:
import statistics as st

In [8]:
st.mean(my_array)

4

In [9]:
st.mode(my_array)

3

In [10]:
st.median(my_array)

4

In [11]:
st.stdev(my_array)

3.1622776601683795

In [16]:
st.variance(my_array)

10

# 2D Array

In [22]:
my_array2 = np.array([[2,6,1],[9,5,7],[6,7,3]])
my_array2

array([[2, 6, 1],
       [9, 5, 7],
       [6, 7, 3]])

In [37]:
np.size(my_array2)

9

In [25]:
np.mean(my_array2,axis=0)

array([5.66666667, 6.        , 3.66666667])

In [26]:
np.mean(my_array2,axis=1)

array([3.        , 7.        , 5.33333333])

In [29]:
np.median(my_array2)

6.0

In [30]:
np.median(my_array2,axis=0)

array([6., 6., 3.])

In [32]:
np.median(my_array2,axis=1)

array([2., 7., 6.])

In [34]:
np.std(my_array2)

2.469567863432541

In [35]:
np.corrcoef(my_array2)

array([[ 1.        , -0.75592895,  0.81705717],
       [-0.75592895,  1.        , -0.24019223],
       [ 0.81705717, -0.24019223,  1.        ]])

# 3D Array

In [36]:
my_array3 = np.array([[[5,8,1],[9,3,7]],[[7,1,6],[8,2,5]],[[1,9,5],[6,5,4]]])
my_array3

array([[[5, 8, 1],
        [9, 3, 7]],

       [[7, 1, 6],
        [8, 2, 5]],

       [[1, 9, 5],
        [6, 5, 4]]])

In [38]:
np.size(my_array3)

18

In [39]:
print(my_array.ndim)

1


In [41]:
print(my_array2.ndim)

2


In [42]:
print(my_array3.ndim)

3


# Automatic n-dimension array creation

In [43]:
array = np.array([9,5,1,7,5,3,6,5,4],ndmin=6)
array

array([[[[[[9, 5, 1, 7, 5, 3, 6, 5, 4]]]]]])

# Using loop in n- dimension array

In [44]:
for x in my_array:
    print(x)

3
9
4
2
8
6
1
0
7
3
9


In [45]:
for x in my_array2:
    print(x)

[2 6 1]
[9 5 7]
[6 7 3]


In [47]:
for x in my_array2:
    for y in x:
        print(y)

2
6
1
9
5
7
6
7
3


In [49]:
for x in my_array3:
    print(x)

[[5 8 1]
 [9 3 7]]
[[7 1 6]
 [8 2 5]]
[[1 9 5]
 [6 5 4]]


In [50]:

for x in my_array3:
    for y in x:
        for z in y:
            print(z)

5
8
1
9
3
7
7
1
6
8
2
5
1
9
5
6
5
4


# Scalar Math in array...

In [51]:
np.add(my_array,3)

array([ 6, 12,  7,  5, 11,  9,  4,  3, 10,  6, 12])

In [52]:
np.add(my_array2,3)

array([[ 5,  9,  4],
       [12,  8, 10],
       [ 9, 10,  6]])

In [53]:
np.add(my_array3,8)

array([[[13, 16,  9],
        [17, 11, 15]],

       [[15,  9, 14],
        [16, 10, 13]],

       [[ 9, 17, 13],
        [14, 13, 12]]])

In [56]:
np.subtract(my_array,1)

array([ 2,  8,  3,  1,  7,  5,  0, -1,  6,  2,  8])

In [57]:
np.subtract(my_array2,3)

array([[-1,  3, -2],
       [ 6,  2,  4],
       [ 3,  4,  0]])

In [58]:
np.subtract(my_array3,4)

array([[[ 1,  4, -3],
        [ 5, -1,  3]],

       [[ 3, -3,  2],
        [ 4, -2,  1]],

       [[-3,  5,  1],
        [ 2,  1,  0]]])

In [61]:
np.multiply(my_array,3)

array([ 9, 27, 12,  6, 24, 18,  3,  0, 21,  9, 27])

In [62]:
np.multiply(my_array2,5)

array([[10, 30,  5],
       [45, 25, 35],
       [30, 35, 15]])

In [63]:
np.multiply(my_array3,6)

array([[[30, 48,  6],
        [54, 18, 42]],

       [[42,  6, 36],
        [48, 12, 30]],

       [[ 6, 54, 30],
        [36, 30, 24]]])

In [64]:
np.divide(my_array,5)

array([0.6, 1.8, 0.8, 0.4, 1.6, 1.2, 0.2, 0. , 1.4, 0.6, 1.8])

In [65]:
np.divide(my_array2,8)

array([[0.25 , 0.75 , 0.125],
       [1.125, 0.625, 0.875],
       [0.75 , 0.875, 0.375]])

In [66]:
np.divide(my_array3,8)

array([[[0.625, 1.   , 0.125],
        [1.125, 0.375, 0.875]],

       [[0.875, 0.125, 0.75 ],
        [1.   , 0.25 , 0.625]],

       [[0.125, 1.125, 0.625],
        [0.75 , 0.625, 0.5  ]]])

In [67]:
np.power(my_array,8)

array([    6561, 43046721,    65536,      256, 16777216,  1679616,
              1,        0,  5764801,     6561, 43046721], dtype=int32)

In [68]:
np.power(my_array2,6)

array([[    64,  46656,      1],
       [531441,  15625, 117649],
       [ 46656, 117649,    729]], dtype=int32)

In [69]:
np.power(my_array2,3)

array([[  8, 216,   1],
       [729, 125, 343],
       [216, 343,  27]], dtype=int32)

# Vector Math in n-dimension array...

In [70]:
array1 = np.array([9,3,4,7,6,1,2])
array2 = np.array([7,1,6,4,8,3,1])


In [71]:
np.size(array1)


7

In [72]:
np.size(array2)

7

In [73]:
print(array1.ndim)

1


In [74]:
print(array1.ndim)

1


In [75]:
np.add(array1 , array2)

array([16,  4, 10, 11, 14,  4,  3])

In [76]:
np.subtract(array1 , array2)

array([ 2,  2, -2,  3, -2, -2,  1])

In [77]:
np.multiply(array1 , array2)

array([63,  3, 24, 28, 48,  3,  2])

In [78]:
np.power(array1,array2)

array([4782969,       3,    4096,    2401, 1679616,       1,       2])

In [80]:
np.array_equal(array1,array2)

False

In [81]:
np.sqrt(array1)

array([3.        , 1.73205081, 2.        , 2.64575131, 2.44948974,
       1.        , 1.41421356])

In [82]:
np.sqrt(array2)

array([2.64575131, 1.        , 2.44948974, 2.        , 2.82842712,
       1.73205081, 1.        ])

In [83]:
np.log(array1)

array([2.19722458, 1.09861229, 1.38629436, 1.94591015, 1.79175947,
       0.        , 0.69314718])

In [84]:
np.log(array2)

array([1.94591015, 0.        , 1.79175947, 1.38629436, 2.07944154,
       1.09861229, 0.        ])

In [85]:
np.sin(array1)

array([ 0.41211849,  0.14112001, -0.7568025 ,  0.6569866 , -0.2794155 ,
        0.84147098,  0.90929743])

In [86]:
np.sin(array2)

array([ 0.6569866 ,  0.84147098, -0.2794155 , -0.7568025 ,  0.98935825,
        0.14112001,  0.84147098])

# Sorting in n- dimension array....


In [87]:
np.sort(array1)

array([1, 2, 3, 4, 6, 7, 9])

In [88]:
np.sort(array2)

array([1, 1, 3, 4, 6, 7, 8])

In [90]:
my_array2.T

array([[2, 9, 6],
       [6, 5, 7],
       [1, 7, 3]])

In [94]:
a=np.insert(my_array,3,9)

In [95]:
my_array

array([3, 9, 4, 2, 8, 6, 1, 0, 7, 3, 9])

# Splittiing


In [96]:
np.split(a,6)

[array([3, 9]),
 array([4, 9]),
 array([2, 8]),
 array([6, 1]),
 array([0, 7]),
 array([3, 9])]

# Random n-dimension array...

In [97]:
from numpy import random

In [98]:
x = random.rand(5,9)

In [99]:
print(x)

[[0.65035338 0.96952438 0.63931841 0.83232809 0.65441013 0.94036902
  0.09269269 0.76852491 0.9250291 ]
 [0.8072471  0.74309256 0.32340864 0.39696822 0.03844641 0.349183
  0.93735816 0.37423539 0.03047568]
 [0.62788243 0.77064115 0.98609122 0.1935995  0.58241176 0.21526014
  0.85129794 0.8680295  0.19979969]
 [0.55938642 0.35495848 0.57275001 0.80282517 0.17132052 0.82248465
  0.80509476 0.43562971 0.80384387]
 [0.85562577 0.36431251 0.20208921 0.85412119 0.35051813 0.58501809
  0.51747667 0.84843249 0.61909732]]


In [100]:
y = random.rand(3)

In [101]:
print(y)

[0.54852752 0.02679508 0.00278256]


In [107]:
z = random.rand(9,1)

In [108]:
print(z)

[[0.11432826]
 [0.41596817]
 [0.68566673]
 [0.50492901]
 [0.52359405]
 [0.63284771]
 [0.23856172]
 [0.91320376]
 [0.50443756]]
