In [1]:
import numpy as np

In [2]:
My_Array = np.array([2,56,8,6,1,84,1,48,5,99,9,])
My_Array

array([ 2, 56,  8,  6,  1, 84,  1, 48,  5, 99,  9])

In [3]:
print(type(My_Array))

<class 'numpy.ndarray'>


In [4]:
import statistics as st

In [5]:
st.mean(My_Array)

29

In [6]:
st.mode(My_Array)

1

# 2D Array

In [7]:
My_Array_2 = np.array([[2,9,4],[3,7,1],[7,2,8]])


In [8]:
print(My_Array_2)

[[2 9 4]
 [3 7 1]
 [7 2 8]]


# 3D Array

In [9]:
My_Array_3 = np.array([[[2,8,3],[3,3,8]],[[1,9,4],[7,9,8]]])
print(My_Array_3)

[[[2 8 3]
  [3 3 8]]

 [[1 9 4]
  [7 9 8]]]


In [10]:
print(My_Array.ndim)
print(My_Array_2.ndim)
print(My_Array_3.ndim)

1
2
3


# Automatic n- dimension array creation

In [11]:
array = np.array([2,9,4,8,3],ndmin=5)
print(array)

[[[[[2 9 4 8 3]]]]]


In [12]:
array = np.array([9,7,3,1,5,3],ndmin=8)
print(array)

[[[[[[[[9 7 3 1 5 3]]]]]]]]


# Ascess element in the n-dimension array...


In [13]:
print(My_Array[3])

6


In [14]:
My_Array[3]=8
print(My_Array)

[ 2 56  8  8  1 84  1 48  5 99  9]


# Use Looping in n-dimension array

In [15]:
for x in My_Array:
    print(x)

2
56
8
8
1
84
1
48
5
99
9


In [16]:
for x in My_Array_2:
    print(x)

[2 9 4]
[3 7 1]
[7 2 8]


In [17]:
for x in My_Array_3:
    print(x)

[[2 8 3]
 [3 3 8]]
[[1 9 4]
 [7 9 8]]


In [18]:
for x in My_Array_2:
    for y in x:
        print(y)

2
9
4
3
7
1
7
2
8


In [19]:
for x in My_Array_3:
    for y in x:
        for z in y:
            print(z)

2
8
3
3
3
8
1
9
4
7
9
8


# Scalar Math in array...


In [20]:
np.add(My_Array,1)


array([  3,  57,   9,   9,   2,  85,   2,  49,   6, 100,  10])

In [21]:
np.subtract(My_Array,2)

array([ 0, 54,  6,  6, -1, 82, -1, 46,  3, 97,  7])

In [22]:
print(My_Array)

[ 2 56  8  8  1 84  1 48  5 99  9]


In [23]:
np.add(My_Array_2,2)

array([[ 4, 11,  6],
       [ 5,  9,  3],
       [ 9,  4, 10]])

In [24]:
np.subtract(My_Array_2,2)

array([[ 0,  7,  2],
       [ 1,  5, -1],
       [ 5,  0,  6]])

In [25]:
np.multiply(My_Array,3)

array([  6, 168,  24,  24,   3, 252,   3, 144,  15, 297,  27])

In [26]:
np.multiply(My_Array_2,6)

array([[12, 54, 24],
       [18, 42,  6],
       [42, 12, 48]])

In [27]:
np.divide(My_Array,3)

array([ 0.66666667, 18.66666667,  2.66666667,  2.66666667,  0.33333333,
       28.        ,  0.33333333, 16.        ,  1.66666667, 33.        ,
        3.        ])

In [28]:
np.divide(My_Array_2,3)

array([[0.66666667, 3.        , 1.33333333],
       [1.        , 2.33333333, 0.33333333],
       [2.33333333, 0.66666667, 2.66666667]])

In [29]:
np.power(My_Array,4)

array([      16,  9834496,     4096,     4096,        1, 49787136,
              1,  5308416,      625, 96059601,     6561], dtype=int32)

In [30]:
np.power(My_Array_2,3)

array([[  8, 729,  64],
       [ 27, 343,   1],
       [343,   8, 512]], dtype=int32)

# Vector Math in n-dimension array..

In [31]:
arr1 = np.array([3,8,1,9,6,7,2,6,4,9,3,5])
np.ndim(arr1)

1

In [32]:
arr1.size

12

In [33]:
arr2 = np.array([5,9,1,2,7,3,6,1,9,2,4,8])
np.ndim(arr2)
arr2.size

12

In [34]:
np.add(arr1,arr2)

array([ 8, 17,  2, 11, 13, 10,  8,  7, 13, 11,  7, 13])

In [35]:
np.subtract(arr1,arr2)

array([-2, -1,  0,  7, -1,  4, -4,  5, -5,  7, -1, -3])

In [36]:
np.subtract(arr2,arr1)

array([ 2,  1,  0, -7,  1, -4,  4, -5,  5, -7,  1,  3])

In [37]:
np.multiply(arr1,arr2)

array([15, 72,  1, 18, 42, 21, 12,  6, 36, 18, 12, 40])

In [38]:
np.power(arr1,arr2)

array([      243, 134217728,         1,        81,    279936,       343,
              64,         6,    262144,        81,        81,    390625])

In [39]:
np.array_equal(arr1,arr2)

False

In [40]:
np.sqrt(arr1)

array([1.73205081, 2.82842712, 1.        , 3.        , 2.44948974,
       2.64575131, 1.41421356, 2.44948974, 2.        , 3.        ,
       1.73205081, 2.23606798])

In [41]:
np.sqrt(arr2)

array([2.23606798, 3.        , 1.        , 1.41421356, 2.64575131,
       1.73205081, 2.44948974, 1.        , 3.        , 1.41421356,
       2.        , 2.82842712])

In [42]:
np.sin(arr1)

array([ 0.14112001,  0.98935825,  0.84147098,  0.41211849, -0.2794155 ,
        0.6569866 ,  0.90929743, -0.2794155 , -0.7568025 ,  0.41211849,
        0.14112001, -0.95892427])

In [43]:
np.sin(arr2)

array([-0.95892427,  0.41211849,  0.84147098,  0.90929743,  0.6569866 ,
        0.14112001, -0.2794155 ,  0.84147098,  0.41211849,  0.90929743,
       -0.7568025 ,  0.98935825])

In [44]:
np.log(arr1)

array([1.09861229, 2.07944154, 0.        , 2.19722458, 1.79175947,
       1.94591015, 0.69314718, 1.79175947, 1.38629436, 2.19722458,
       1.09861229, 1.60943791])

In [45]:
np.log(arr2)

array([1.60943791, 2.19722458, 0.        , 0.69314718, 1.94591015,
       1.09861229, 1.79175947, 0.        , 2.19722458, 0.69314718,
       1.38629436, 2.07944154])

# Statistics in n-dimesion array.....


In [46]:
np.mean(My_Array)

29.181818181818183

In [47]:
np.mean(My_Array_2,axis=1)

array([5.        , 3.66666667, 5.66666667])

In [48]:
np.mean(My_Array_2,axis=0)

array([4.        , 6.        , 4.33333333])

In [49]:
np.sum(My_Array)

321

In [50]:
np.sum(My_Array_2)

43

In [51]:
np.min(My_Array)

1

In [52]:
np.min(My_Array_2)

1

In [53]:
np.var(My_Array)

1197.2396694214874

In [54]:
np.std(My_Array)

34.60115127306442

In [55]:
np.std(My_Array_2,1)

array([2.94392029, 2.49443826, 2.62466929])

In [56]:
np.std(My_Array_2,axis=0)

array([2.1602469 , 2.94392029, 2.86744176])

In [57]:
np.corrcoef(My_Array)

1.0

In [58]:
np.corrcoef(My_Array_2)

array([[ 1.        ,  0.81705717, -0.90593576],
       [ 0.81705717,  1.        , -0.98432414],
       [-0.90593576, -0.98432414,  1.        ]])

# sorting in n-dimension array


In [59]:
np.sort(My_Array)

array([ 1,  1,  2,  5,  8,  8,  9, 48, 56, 84, 99])

In [60]:
My_Array_2.T

array([[2, 3, 7],
       [9, 7, 2],
       [4, 1, 8]])

In [61]:
np.insert(My_Array,3,3)

array([ 2, 56,  8,  3,  8,  1, 84,  1, 48,  5, 99,  9])

In [62]:
print(My_Array)

[ 2 56  8  8  1 84  1 48  5 99  9]


In [63]:
np.append(My_Array,3)

array([ 2, 56,  8,  8,  1, 84,  1, 48,  5, 99,  9,  3])

In [64]:
print(My_Array)

[ 2 56  8  8  1 84  1 48  5 99  9]


# Splitting

In [66]:
np.split(arr1,3)

[array([3, 8, 1, 9]), array([6, 7, 2, 6]), array([4, 9, 3, 5])]

In [67]:
np.split(arr1,4)

[array([3, 8, 1]), array([9, 6, 7]), array([2, 6, 4]), array([9, 3, 5])]

# Searching in an array.....

In [68]:
np.where(My_Array==48)

(array([7], dtype=int64),)

In [69]:
np.where(My_Array==1)

(array([4, 6], dtype=int64),)

# Random Array.....

In [70]:
from numpy import random

In [71]:
x= random.randint(200)

In [72]:
print(x)

188


In [73]:
print(x)

188


In [74]:
x= random.randint(200)
print(x)

16


In [75]:
y = random.randint(100,size=(13))

In [76]:
print(y)

[77 73 30 37 72 21 83 91 48  2  8 51 98]


In [77]:
x= random.rand(6,8)

In [78]:
print(x)

[[0.35997122 0.67850049 0.48133078 0.01280936 0.08318043 0.7972328
  0.80219036 0.25409361]
 [0.23773102 0.1905718  0.29590424 0.15061661 0.59485118 0.7920875
  0.34604131 0.92966748]
 [0.28027012 0.34595984 0.81215524 0.48983943 0.45545017 0.22898146
  0.48515015 0.83494701]
 [0.42234867 0.52574252 0.74861363 0.65288432 0.65620823 0.84271428
  0.54349813 0.6245305 ]
 [0.49323145 0.49447831 0.14221249 0.05939759 0.04527353 0.18091691
  0.65836296 0.58285319]
 [0.23719537 0.73064351 0.79329697 0.66405353 0.03326606 0.40660478
  0.13852267 0.61492345]]
