In [1]:
import numpy as np

In [2]:
My_Array = np.array([6,8,3,4,7,9,2,1,3,4,7,3,2,8,25,1,8])

In [3]:
My_Array

array([ 6,  8,  3,  4,  7,  9,  2,  1,  3,  4,  7,  3,  2,  8, 25,  1,  8])

In [4]:
print(type(My_Array))

<class 'numpy.ndarray'>


2D Array

In [5]:
my_array_2 = np.array([[23,5,8],[3,9,4],[6,9,7]])

In [6]:
print(my_array_2)

[[23  5  8]
 [ 3  9  4]
 [ 6  9  7]]


3D Array

In [7]:
my_array_3 = np.array([[[3,9,6],[4,5,2]],[[7,8,1],[3,4,9]]])


In [8]:
print(my_array_3)

[[[3 9 6]
  [4 5 2]]

 [[7 8 1]
  [3 4 9]]]


In [9]:
print(My_Array.ndim)
print(my_array_2.ndim)
print(my_array_3.ndim)

1
2
3


In [10]:
arr = np.array([1,2,3,4,5],ndmin=5)
print(arr)

[[[[[1 2 3 4 5]]]]]


In [11]:
print(My_Array[3])

4


In [12]:
print(my_array_2[2,1])

9


In [13]:
print(My_Array[2:6])

[3 4 7 9]


In [14]:
print(My_Array[1:8:2])

[8 4 9 1]


In [15]:
My_Array[3]=55
print(My_Array)

[ 6  8  3 55  7  9  2  1  3  4  7  3  2  8 25  1  8]


In [16]:
print(My_Array.shape)

(17,)


In [17]:
print(my_array_2.shape)

(3, 3)


In [18]:
print(my_array_3.shape)

(2, 2, 3)


In [19]:
My_Array_4 = np.array([6,8,3,4,7,9,2,1,3,4,7,3,2,8,25,1,8,4])
print(My_Array_4.shape)

(18,)


In [20]:
new_array = My_Array_4.reshape(6,3)
print(new_array)

[[ 6  8  3]
 [ 4  7  9]
 [ 2  1  3]
 [ 4  7  3]
 [ 2  8 25]
 [ 1  8  4]]


In [21]:
for x in My_Array_4:
    print(x)

6
8
3
4
7
9
2
1
3
4
7
3
2
8
25
1
8
4


In [22]:
for x in my_array_2:
    print(x)

[23  5  8]
[3 9 4]
[6 9 7]


In [23]:
for x in my_array_3:
    print(x)

[[3 9 6]
 [4 5 2]]
[[7 8 1]
 [3 4 9]]


In [24]:
for x in my_array_2:
    for y in x:
        print(y)

23
5
8
3
9
4
6
9
7


In [25]:
for x in my_array_3:
    print(x)

[[3 9 6]
 [4 5 2]]
[[7 8 1]
 [3 4 9]]


In [26]:
for x in my_array_3:
    for y in x:
        for z in y:
            print(z)

3
9
6
4
5
2
7
8
1
3
4
9


In [27]:
newarray = np.array_split(My_Array_4,3)
print(newarray)

[array([6, 8, 3, 4, 7, 9]), array([2, 1, 3, 4, 7, 3]), array([ 2,  8, 25,  1,  8,  4])]


In [28]:
newarray = np.array_split(My_Array_4,6)
print(newarray)

[array([6, 8, 3]), array([4, 7, 9]), array([2, 1, 3]), array([4, 7, 3]), array([ 2,  8, 25]), array([1, 8, 4])]


Searching Arrays........



In [29]:
Searching = np.where(My_Array_4==1)
print(Searching)

(array([ 7, 15], dtype=int64),)


In [30]:
Searching = np.where(My_Array_4%2==0)
print(Searching)

(array([ 0,  1,  3,  6,  9, 12, 13, 16, 17], dtype=int64),)


In [31]:
Sort = np.sort(My_Array_4)
print(Sort)

[ 1  1  2  2  3  3  3  4  4  4  6  7  7  8  8  8  9 25]


In [32]:
Sort = np.sort(my_array_2)
print(Sort)

[[ 5  8 23]
 [ 3  4  9]
 [ 6  7  9]]


# Random NumPy

In [33]:
from numpy import random

In [34]:
x = random.randint(100)
print(x)

20


In [35]:
x = random.randint(100)
print(x)

15


In [36]:
x = random.rand()
print(x)

0.636750992657191


Generating Random array

In [37]:
x = random.randint(100,size=(5))
print(x)

[38 71 28 83 59]


In [38]:
x = random.rand(5)
print(x)

[0.71749373 0.34468392 0.37607565 0.85777284 0.16375552]


In [39]:
x = random.rand(3,5)
print(x)

[[0.63318976 0.19612183 0.85622446 0.18202343 0.47119213]
 [0.77978395 0.96541445 0.24837819 0.04314094 0.09616823]
 [0.84092161 0.80371319 0.19792084 0.11807054 0.27117566]]


Choose Random Value


In [40]:
x = random.choice(My_Array_4)
print(x)

2
