#Welcome to numpy#

In [1]:
import numpy as np

In [2]:
myarray=np.array([5,4,3,2,1,6])

In [3]:
myarray

array([5, 4, 3, 2, 1, 6])

In [4]:
myarray.shape

(6,)

In [5]:
myarray.reshape(3,2)

array([[5, 4],
       [3, 2],
       [1, 6]])

In [6]:
myarray.dtype

dtype('int32')

In [7]:
myarray[2]=55

In [8]:
myarray

array([ 5,  4, 55,  2,  1,  6])

In [9]:
listarray=np.array([[1,2,3,],[4,5,6],[7,8,9]])

In [10]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
zeros = np.zeros((2,5))

In [12]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
rng= np.arange(15)

In [14]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
identity = np.identity(45)

In [16]:
identity

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [17]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [18]:
ar = np.array(x)

In [19]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
ar.sum(axis=0)

array([12, 15, 18])

In [21]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [22]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [23]:
ar.flat

In [24]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [25]:
ar.nbytes

36

In [26]:
ar.min

<function ndarray.min>

In [27]:
ar.min()

1

In [28]:
ar.max()

9

In [29]:
np.count_nonzero(ar)

9

In [31]:
a=np.arange(3,20,2)

In [32]:
print(a)

[ 3  5  7  9 11 13 15 17 19]


In [37]:
print(a.dtype)

int32


In [38]:
a.astype("float")

array([ 3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])